name: Auto update stdpp

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every Monday at 4:15 am
    - cron:  '15 4 * * 1'
  workflow_dispatch:

jobs:
  stdpp-auto-update:
    name: Stdpp auto update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: "Update"
        run: |
          cd $GITHUB_WORKSPACE
          gh config set prompt disabled
          git config user.email "jenda.tusil@gmail.com"
          git config user.name "Jan Tusil (GH Actions)"
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          ./scripts/update-deps.sh
