name: Auto update stdpp

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every Monday at 4:15 am
    - cron:  '15 4 * * 1'
  workflow_dispatch:

jobs:
  stdpp-auto-update:
    name: Stdpp auto update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          ./scripts/update-deps.sh
