name: Auto update stdpp

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every Monday at 4:15 am
    - cron:  '15 4 * * 1'
  workflow_dispatch:

jobs:
  stdpp-auto-update:
    name: Stdpp auto update
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        run:
          ./scripts/update-deps
